/**
 * OQIM — game-page Uzbek strings (game.md).
 * Game-scope dictionary (shared uz.ts stays untouched).
 */
export const g = {
  shell: {
    round: (n: number) => `Aylana ${n}`,
    ratRace: "Aylana",
    fastTrack: "Erkinlik",
    settings: "Sozlamalar",
    rules: "Qoidalar",
    knowledge: "Bilim",
    clients: "Mijozlar",
    saveAndExit: "O'yinni saqlash va chiqish",
    restart: "Qayta boshlash",
    haptics: "Tebranish (haptik)",
    speed: "Harakat tezligi",
    slow: "Sekin",
    normal: "O'rtacha",
    fast: "Tez",
    close: "Yopish",
  },
  resume: {
    title: "Saqlangan o'yin topildi",
    resume: "Davom etish",
    newGame: "Yangi o'yin",
    turn: (n: number) => `Aylana ${n}`,
  },
  setup: {
    title: "O'yinni sozlash",
    steps: ["Kvadrant", "Qahramon", "Raqiblar", "Orzu"],
    yourName: "Ismingiz",
    namePlaceholder: "Masalan, Aziza",
    drawCard: "Kasb kartasini ochish",
    professionCardBack: "KASB",
    reroll: "Boshqa kasb tanlash",
    rerollHint: "Taqdirdan qochib bo'lmaydi",
    salary: "Maosh",
    expenses: "Xarajatlar",
    loanPayments: "Qarz to'lovlari",
    cashflow: "Oylik naqd oqim",
    savings: "Jamg'arma",
    debts: "Qarzlar",
    next: "Keyingisi",
    back: "Orqaga",
    rivals: "Raqiblar (botlar)",
    botCount: "Botlar soni",
    yourDream: "Orzuingizni tanlang",
    dreamStamp: "SENING ORZUING",
    start: "O'yinni boshlash",
    solo: "Yolg'iz o'ynash",
    botCountLabel: (n: number) => (n === 0 ? "Yolg'iz o'ynash" : `${n} ta bot`),
    heroMode: "Qahramon tanlash",
    customMode: "O'z personajingizni yarating",
    heroPickTitle: "Qahramonni tanlang",
    heroPickSub: "Katalogdan personaj tanlang — qahramon yoki kasb",
    flipCards: "Kartalarni ochish",
    // fix-15 (P1): to'liq personaj katalogi
    catalogSearch: "Qidirish...",
    filterAll: "Hammasi",
    filterHeroes: "Qahramonlar",
    filterProfessions: "Kasblar",
    catalogEmpty: "Hech narsa topilmadi",
    creditRow: "Kredit to'lovi",
    // fix-15 (P2): qiyinlik tanlovi
    difficultyTitle: "Qiyinlik",
    diffRecommended: "Tavsiya etilgan (personaj holatiga mos)",
    diffRecommendedHint: "Boshlang'ich shartlar o'zgarmaydi",
    diffEasyHint: "Boshlang'ich naqd +30%",
    diffHardHint: "Boshlang'ich naqd −20% va maosh −5% (past stavka)",
    ability: "Qobiliyat",
    customTitle: "O'z personajingizni yarating",
    customName: "Ism",
    customProfession: "Kasb nomi",
    customProfessionPlaceholder: "Masalan, Shifokor yoki Dasturchi",
    customSalary: "Oylik maosh (so'm)",
    customExpHousing: "Uy-joy (ijara/kommunal)",
    customExpFood: "Oziq-ovqat",
    customExpTransport: "Transport",
    customExpEducation: "Ta'lim/bolalar",
    customExpOther: "Boshqa",
    customExpTotal: "Jami",
    customCash: "Boshlang'ich naqd pul (so'm)",
    customLoans: "Qarzlar (ixtiyoriy)",
    customLoanMortgage: "Ipoteka",
    customLoanAuto: "Avto krediti",
    customLoanCard: "Kredit karta",
    customLoanRemaining: "Qolgan summa",
    customLoanRate: "Yillik foiz (%)",
    customLoanMonths: "Muddat (oy)",
    customLoanComputed: (monthly: string) => `Oylik to'lov: ~${monthly}`,
    customLoanHint: "Summa kiritilgan qarz uchun stavka va muddat ham 0 dan katta bo'lishi shart",
    customQuadrant: "Kvadrant",
    customFlow: "Oylik naqd oqim",
    // fix-16 (X2): o'yin uslubi tanlovi
    boardModeTitle: "O'yin uslubi",
    boardClassic: "🎲 Klassik doska",
    boardClassicDesc: "Zar, 30 katak — mavjud tajriba",
    boardPath: "⛰️ Hayot cho'qqisi",
    boardPathDesc: "Bosqichma-bosqich moliyaviy cho'qqiga ko'tariling",
    // fix-17 (R3): reja rejimi tanlovi
    boardPlan: "🗓 Reja rejimi",
    boardPlanDesc: "Oyingizni o'zingiz rejalang — zar emas, strategiya",
    badgeNew: "YANGI",
  },
  // fix-17 (R3): reja rejimi — fix-18 (E): haftalik tuman
  plan: {
    title: "🗓 Reja rejimi",
    monthTitle: (n: number) => `${n}-oy rejasi`,
    planPrompt: "20 faol kunga plitkalar joylashtiring",
    pickTile: "Avval pastdan plitka tanlang",
    tapDay: "Kunni bosing — tanlangan plitka qo'yiladi",
    tapDayRemove: "Band kunga yana bosing — plitka olib tashlanadi",
    filled: (n: number, total: number) => `${n}/${total} kun to'ldirildi`,
    autofill: "✨ Avto-to'ldirish",
    run: "▶️ Oyni bajarish",
    running: "Oy bajarilmoqda…",
    dayLabel: (n: number) => `${n}-kun`,
    workDay: "💼 Ish kuni — maosh hisobiga yozildi",
    restDay: "🌿 Dam olish kuni — tinch kun",
    avans: "💸 Avans olish",
    avansLocked: (day: number) => `Avans ${day}-kundan keyin olinadi`,
    avansTaken: "Avans olingan",
    salaryNote: (days: number) => `Bu oy ${days} ish kuni — maosh ${days}/20 nisbatda`,
    executingDay: (n: number, total: number) => `${n}/${total} kun bajarilmoqda…`,
    botPlanning: "reja tuzmoqda…",
    // fix-18 (E): haftalik oqim
    weekTitle: (n: number, total: number) => `${n}-hafta / ${total}`,
    weekPrompt: "Shu haftaning 5 kunini rejalashtiring",
    unknownWeek: "❓ Noma'lum hafta",
    unknownWeekHint: "Joriy hafta tugagach ochiladi",
    runWeek: "▶️ Haftani bajarish",
    runMonthEnd: "▶️ Oyni yakunlash",
    weekDone: (n: number) => `${n}-hafta bajarildi ✓`,
    weekSalaryNote: (days: number) => `Shu hafta ${days} ish kuni`,
  },
  // fix-16 (X3): yo'l xaritasi rejimi — fix-18 (G): "Hayot cho'qqisi"
  path: {
    choosePrompt: "Yo'lni tanlang",
    monthPayday: (n: number) => `${n}-oy · Ish haqi`,
    rest: "Dam oldingiz — tinch kun",
    exchangeTitle: "Birja",
    exchangeBody: "Bozor shahrigacha keldingiz — birja oynasi ochildi.",
    fogLabel: "Noma'lum",
    // fix-18 (G): tog bosqichlari (kvadrant zonalariga bog'langan)
    summit: "🚩 CHO'QQI — moliyaviy erkinlik",
    stages: [
      { icon: "🌱", name: "BOSHLASH", zone: "E zonasi" },
      { icon: "🏠", name: "O'SISH", zone: "S zonasi" },
      { icon: "🏪", name: "QURISH", zone: "B zonasi" },
      { icon: "🏭", name: "MEROS", zone: "I zonasi" },
    ] as { icon: string; name: string; zone: string }[],
    zoneLocked: "Kvadrant ochilmagan",
    youAreHere: "Siz shu yerdasiz",
  },
  quadrant: {
    title: "Siz qaysi kvadrantdanasiz?",
    sub: "Moliyaviy kvadrantingizni aniqlash uchun 3 ta savolga javob bering",
    result: (name: string) => `Sizning kvadrantingiz: ${name}`,
    override: "Qo'lda o'zgartirish:",
    offQuadrant: "Kvadrantingizdan tashqaridagi qahramon",
    names: {
      E: "E — Yollanma xodim",
      S: "S — O'z ishini o'zi qiluvchi",
      B: "B — Biznes egasi",
      I: "I — Investor",
    } as Record<string, string>,
    desc: {
      E: "Siz xavfsizlikni qadrlaysiz: barqaror maosh — asosiy daromad manbangiz. E kvadranti xavfsizlik va barqarorlikni so'raydi. Maoshga tayanish qulay, lekin vaqtingizni sotib olasiz — passiv daromad sizni erkin qiladi.",
      S: "Siz o'z ishingizni o'zingiz qilasiz: mutaxassis yoki kichik ustaxona egasi. S kvadranti mahorat va mukammallikni so'raydi. Lekin siz ishlamasangiz, daromad to'xtaydi — tizim qurishni o'rganing.",
      B: "Siz biznes egasisiz: boshqalar sizning tizimingizda ishlaydi. B kvadranti jamoa va tizim qurishni so'raydi. Sizning vazifangiz — tizim sizsiz ham ishlashini ta'minlash.",
      I: "Siz investorsiz: pulingiz siz uchun ishlaydi. I kvadranti — pul ishlaydigan joy. Aktivlar haqidagi bilimingiz — eng katta kapitallingiz.",
    } as Record<string, string>,
    questions: [
      {
        q: "Asosiy daromadingiz qayerdan keladi?",
        options: [
          { label: "Ish haqimdan (maosh)", q: "E" },
          { label: "O'z kasbim/xizmatimdan", q: "S" },
          { label: "Kompaniyamdan (biznesimdan)", q: "B" },
          { label: "Investitsiyalarimdan", q: "I" },
        ],
      },
      {
        q: "Ishlamay qolsangiz, daromad to'xtaydimi?",
        options: [
          { label: "Ha, maosh darhol to'xtaydi", q: "E" },
          { label: "Mijozlarimsiz daromad yo'q", q: "S" },
          { label: "Yo'q, biznesim o'zi ishlayveradi", q: "B" },
          { label: "Yo'q, kapitalim men uchun ishlaydi", q: "I" },
        ],
      },
      {
        q: "Bo'sh mablag'ingizni qayerga yo'naltirasiz?",
        options: [
          { label: "Omonatga / jamg'armaga", q: "E" },
          { label: "O'z kasbimga (uskuna, kurslar)", q: "S" },
          { label: "Biznesni kengaytirishga", q: "B" },
          { label: "Aktivlarga (aksiya, mulk)", q: "I" },
        ],
      },
    ] as { q: string; options: { label: string; q: string }[] }[],
  },
  credit: {
    title: "Kredit reytingi",
    zoneGood: "A'lo",
    zoneMid: "O'rtacha",
    zoneBad: "Past",
    scoreTooLow: (have: number, need: number) => `Reyting yetarli emas (sizda: ${have}, kerak: ${need})`,
    noCollateral: "Garovga yaroqsiz aktiv (kripto/riskli bitimlarga kredit yo'q)",
    requiresScore: (n: number) => `Reyting ≥ ${n} kerak`,
    incomeCap: (max: string) => `Daromadingizga ko'ra limit: ${max} (6× oylik daromad)`,
    logNewLoan: "📊 Kredit reytingi −5 (yangi kredit olindi)",
    logPayoff: "📊 Kredit reytingi +15 (kredit muddatidan oldin yopildi)",
    logEarlyPayoff: "📊 Kredit reytingi +5 (kredit to'liq yopildi)",
    logEmergency: "📊 Kredit reytingi −20 (shoshilinch qarz)",
    logBankruptcy: "📊 Kredit reytingi −150 (bankrotlik)",
  },
  dilemma: {
    choose: "Tanlov qiling",
    lesson: "Dars:",
  },
  news: {
    label: "Bozor yangiliklari",
    effectUp: (target: string) => `${target} daromadi +10%`,
    effectDown: (target: string) => `${target} daromadi −10%`,
    drawn: (text: string) => `Bozor yangiligi: ${text}`,
  },
  /* fix-10 (F2): Bildirishnomalar markazi (🔔) */
  notif: {
    title: "Bildirishnomalar",
    empty: "Hozircha bildirishnoma yo'q",
    emptyHint: "Yangiliklar, hodisalar va muhim voqealar shu yerda ko'rinadi",
    dayChip: (n: number) => `${n}-kun`,
    monthChip: (n: number) => `${n}-oy`,
    payday: "Oy kuni",
    avans: "Avans olindi",
    news: "Bozor yangiligi",
    event: "Hodisa natijasi",
    loanClosed: "Kredit yopildi",
    quadrant: "Kvadrant o'sishi",
    clients: "Yangi mijoz",
    dream: "Orzu",
    sectors: "Ta'sirlangan sektorlar",
    sectorLabels: {
      bank: "Banklar",
      sanoat: "Sanoat",
      telekom: "Telekom",
      energetika: "Energetika",
      qishloq: "Qishloq xo'jaligi",
      texnologiya: "Texnologiya",
      oltin: "Oltin",
      obligatsiya: "Obligatsiyalar",
    } as Record<string, string>,
  },
  turn: {
    yourTurn: "Sening navbating",
    botTurn: (name: string) => `${name} o'ynamoqda`,
    roll: "Zar tashlash",
    endTurn: "Davom etish",
    skipped: (name: string) => `${name} navbatni o'tkazib yubordi`,
    watching: "Kuzatilmoqda...",
    rollHint: "Zar tashlash uchun bosing",
    discarded: (n: number) => `O'tkazilgan: ${n}`,
  },
  cells: {
    payday: "Oy kun",
    avans: "Avans",
    opportunity: "Imkoniyat",
    market: "Bozor",
    event: "Hodisa",
    charity: "Xayriya",
    doodad: "Kutilmagan xarajat",
    baby: "Farzand tug'ildi",
    downsized: "Ishsizlik",
    weekend: "Dam olish kuni",
    bonus: "Naqd bonus",
    business: "Yirik biznes",
    dream: "Orzu",
    audit: "Soliq auditi",
  },
  payday: {
    toast: (amount: string) => `Oy kuni: ${amount}`,
    negative: (amount: string) => `To'lovlar daromaddan oshdi: ${amount}`,
    avansDeducted: (amount: string) => `Ish haqi (avans ayirilgan): ${amount}`,
  },
  calendar: {
    day: (n: number) => `Oyni ${n}-kuni`,
    toPayday: (n: number) => `Oylikgacha ${n} kun`,
    toAvans: (n: number) => `Avansgacha ${n} kun`,
    monthEnded: "🗓 Oy tugadi! Yangi oy boshlandi.",
    month: (n: number) => `${n}-oy`,
  },
  avans: {
    title: "Avans",
    /** kvadrantga qarab daromad manbai nomi (matematika bir xil — 30%) */
    source: {
      E: "maoshning",
      S: "shaxsiy daromadning",
      B: "biznes daromadining",
      I: "investitsiya daromadining",
    } as Record<string, string>,
    received: (amount: string, source: string) => `Avans (maosh−kreditlar 30%): +${amount} (${source})`,
    /** kredit to'lovlari maoshni yutganda (fix-12) */
    eatenByLoans: "Avans: kredit to'lovlari maoshni yutdi — 0 so'm",
    unemployed: "Ishsizlikda avans yo'q",
  },
  homeExpense: {
    title: "Uy xarajati",
    log: (title: string, amount: string) => `Uy xarajati: ${title} — −${amount}`,
  },
  deal: {
    pickTitle: "Imkoniyat!",
    pickSub: "Qaysi bitim kartasini olasiz?",
    small: "Kichik bitim",
    big: "Katta bitim",
    price: "Narx",
    down: "Boshlang'ich to'lov",
    cashflowRow: "Oylik oqim",
    roi: "ROI",
    buy: "Sotib olish",
    pass: "O'tkazib yuborish",
    cantAfford: "Naqd pul yetarli emas",
    riskLevel: (n: number) => `Xavf: ${n}/5`,
    liquidity: (n: number) => `Likvidlik: ${n}/5`,
    analystBadge: "Tahliliy",
    analystBadgeHint: "Investitsiya kursi: ROI tahlili faol",
    bankLoan: "Bankdan qarz olish (30%/yil)",
    buyCash: "Naqd sotib olish",
    buyCashSub: (amount: string) => `Hozir to'lanadi: ${amount}`,
    buyLoan: "Kreditga olish",
    buyLoanSub: (monthly: string, months: number) =>
      `Bank qarzi 30%/yil · Oylik: ${monthly} × ${months} oy`,
    loanNotNeeded: "Naqd yetarli — kredit kerak emas",
    buyInstallment: "Bo'lib to'lash",
    buyInstallmentSub: (monthly: string, months: number) =>
      `Oylik: ${monthly} × ${months} oy (+10% ustama)`,
    installmentTooSmall: "5 mln so'mdan arzon bitimlarga mavjud emas",
    installmentFullPrice: "Bu bitim faqat to'liq naqd olinadi",
    knowledgeRequired: (n: number) => `Bilim ${n}-daraja talab qilinadi`,
    knowledgeLocked: (have: number, need: number) =>
      `Bilim yetarli emas (sizda: ${have}/${need}) — ta'lim hodisalari va bitimlar bilim beradi`,
    boughtInstallment: (name: string, title: string) =>
      `${name} «${title}»ni bo'lib to'lashga oldi`,
    mortgageDiscountApplied: "Imtiyozli ipoteka: −20% qo'llanildi",
    bought: (name: string, title: string) => `${name} «${title}» sotib oldi`,
    passed: (name: string) => `${name} bitimni o'tkazib yubordi`,
    construction: "Qurilish jarayonida",
  },
  market: {
    title: "Bozor",
    nothingToSell: "Hozircha sotadigan narsang yo'q",
    sell: "Sotish",
    keep: "Saqlab qolish",
    youReceive: "Qo'lga tegadi",
    sold: (name: string, title: string) => `${name} «${title}»ni sotdi`,
    close: "Yopish",
  },
  event: {
    title: "Hodisa",
    ok: "Davom etish",
    accept: "Qabul qilish",
    decline: "Rad etish",
  },
  charity: {
    title: "Xayriya",
    body: "Oylik daromadingizning 10% ini xayriya qiling — 3 aylana davomida 2 ta zar tashlaysiz.",
    donate: (amount: string) => `Xayriya qilish (${amount})`,
    decline: "Rad etish",
    reward: "3 aylana × 2 zar",
    blocked: (n: number) => `Xayriya katakchasi yopiq (yana ${n} aylana)`,
    donated: (name: string) => `${name} xayriya qildi`,
  },
  doodad: {
    title: "Kutilmagan xarajat",
    payCash: (amount: string) => `Naqd to'lash (${amount})`,
    payCredit: (monthly: string) => `Kreditga olish (${monthly}/oy)`,
    creditHint: "Annuitet: 12 oy, 24%/yil (reyting ≥ 550 kerak)",
    creditScoreLow: (have: number) => `Reyting yetarli emas (sizda: ${have}, kerak: 550)`,
    creditNoDown: "Boshlang'ich to'lovga naqd pul yetarli emas",
    forced: "Naqd yetarli emas — kredit rasmiylashtirildi",
    decline: "Hozircha olmay turish",
    defer: "Keyinroq olaman",
    deferHint: "3 oydan keyin qaytadi — narx +12%",
    deferLimit: "Kechiktirish limiti tugadi",
    deferred: (title: string) => `«${title}» keyinroqqa qoldirildi`,
  },
  weekend: {
    title: "Dam olish kuni",
    chooseHint: "Hafta oxiri rejangizni tanlang",
  },
  lifeEvent: {
    title: "Hayotiy hodisa",
    ok: "Davom etish",
  },
  hero: {
    badge: "Qahramon",
    soloStats: "Yakkaxon o'yin natijalari",
  },
  exchange: {
    title: "Birja",
    subtitle: "Fond birjasi — qimmatli qog'ozlar savdosi",
    portfolio: "Portfel",
    buy: "Sotib olish",
    sell: "Sotish",
    fee: "Komissiya",
    feePct: "0,5%",
    dividend: "Dividend",
    max: "Maks",
    qty: "Soni",
    price: "Narx",
    change: "O'zgarish",
    total: "Jami",
    toPay: "To'lanadi",
    toReceive: "Qo'lga tegadi",
    youOwn: (n: number) => `Sizda: ${n} ta`,
    cantAfford: "Naqd pul yetarli emas",
    nothingToSell: "Bu qog'oz sizda yo'q",
    close: "Yopish",
    confirm: "Tasdiqlash",
    cancel: "Bekor qilish",
    dividendYield: (pct: string) => `Dividend ${pct}%/oy`,
    noDividend: "Dividendsiz",
    volatility: "Tebranish",
    sectors: {
      bank: "Bank",
      sanoat: "Sanoat",
      telekom: "Telekom",
      energetika: "Energetika",
      qishloq: "Qishloq xo'jaligi",
      texnologiya: "Texnologiya",
      oltin: "Oltin",
      obligatsiya: "Obligatsiya",
    } as Record<string, string>,
    introTitle: "Birjaga xush kelibsiz!",
    introRules: [
      "Arzon ola, qimmat sot — narxlar har oy kunida o'zgaradi.",
      "Dividend — passiv daromad: u Kundalik aylanadan chiqishingizga yordam beradi.",
      "Tushkunlikda vahima qilma — bozor vaqt bilan tiklanadi.",
    ],
    introOk: "Tushundim, boshladik!",
    portfolioValue: "Portfel qiymati",
    avgPrice: "O'rtacha narx",
    currentValue: "Joriy qiymat",
    profitLoss: "Foyda/Zarar",
    emptyPortfolio: "Portfel bo'sh — birinchi qog'ozingizni Birjadan sotib oling",
    diversification: "Diversifikatsiya bonusi: dividendlar +10%",
    diversificationHint: "4+ turli sektordan qog'oz ushlab turing",
    dividendsRow: "Birja dividendlari",
    dividendsLog: (amount: string) => `Birja dividendlari: +${amount}`,
    boostActive: (mult: number, months: number) => `Dividendlar ×${mult} · yana ${months} oy`,
    bought: (name: string, qty: number, ticker: string) => `${name} ${qty} ta ${ticker} sotib oldi`,
    sold: (name: string, qty: number, ticker: string) => `${name} ${qty} ta ${ticker} sotdi`,
    buyTitle: (ticker: string) => `${ticker} sotib olish`,
    sellTitle: (ticker: string) => `${ticker} sotish`,
  },
  loans: {
    offers: "Kredit takliflari",
    offersSub: "Bankning amaldagi takliflari — kerakli summani tanlang",
    amount: "Summa",
    monthly: "Oylik to'lov",
    months: (n: number) => `${n} oy`,
    take: "Kredit olish",
    requiresBusiness: "Kamida 1 biznes aktivi kerak",
    taken: (title: string, amount: string) => `${title}: +${amount} olindi`,
    earlyPayoff: "Muddatidan oldin yopish",
    close: "Yopish",
  },
  baby: {
    congrats: "Tabriklaymiz!",
    body: "Oilangizga go'dak qo'shildi",
    cost: "Farzand xarajati",
    feast: "Oilaviy bayram",
    feastBody: "Bolalar uchdan oshdi — shunga bayram qilasiz!",
    ok: "Alloh shukur",
    // fix-15 (P3): farzand oraliq kamida 2 yil
    gapBody: "Farzandlar oralig'i kamida 2 yil bo'lishi kerak — bu safar bayram o'tkazildi",
  },
  // fix-15 (P2): qiyinlik darajasi belgilari
  difficulty: {
    easy: "🟢 Oson",
    medium: "🟡 O'rta",
    hard: "🔴 Qiyin",
  },
  // fix-15 (P4): farzand ta'limi modal oynasi
  childEdu: {
    kgTitle: "Bog'cha tanlovi",
    kgDesc: "Farzandingiz 3 yoshga to'ldi — bog'cha haqida qaror qiling",
    schoolTitle: "Maktab tanlovi",
    schoolDesc: "Farzandingiz 7 yoshga to'ldi — maktab tanlang (bog'cha xarajati to'xtaydi)",
    options: {
      none: { label: "Bog'chasiz", hint: "0 so'm/oy", lesson: "Bog'chasiz tejaysiz, lekin bola erta rivojlanish imkoniyatlarini boy beradi." },
      "kg-state": { label: "Davlat bog'chasi", hint: "+400 ming/oy", lesson: "Davlat bog'chasi — arzon va ishonchli tanlov: bola ijtimoilashadi, xarajat kichik." },
      "kg-private": { label: "Xususiy bog'cha", hint: "+1,2 mln/oy", lesson: "Xususiy bog'cha qimmat, lekin kichik guruhlar va chuqur ta'lim beradi — byudjetdan joy ajrating." },
      "sch-state": { label: "Davlat maktabi", hint: "+300 ming/oy", lesson: "Davlat maktabi arzon — tejalgan pulni investitsiyaga yo'naltirish mumkin." },
      "sch-plus": { label: "Davlat + qo'shimcha kurslar", hint: "+800 ming/oy", lesson: "Qo'shimcha kurslar bilimni kuchaytiradi — ta'limga sarflangan pul eng yaxshi investitsiya." },
      "sch-private": { label: "Xususiy maktab", hint: "+2,5 mln/oy", lesson: "Xususiy maktab qimmat — bunday xarajat passiv daromadsiz byudjetni yoritishi mumkin." },
    } as Record<string, { label: string; hint: string; lesson: string }>,
    choose: "Tanlash",
    ok: "Davom etish",
    ageYears: (n: number) => `${n} yosh`,
    eduLabels: {
      none: "Ta'limsiz",
      "kg-state": "Davlat bog'chasi",
      "kg-private": "Xususiy bog'cha",
      "sch-state": "Davlat maktabi",
      "sch-plus": "Maktab + kurslar",
      "sch-private": "Xususiy maktab",
    } as Record<string, string>,
  },
  downsized: {
    title: "Ishdan bo'shatildingiz",
    body: (amount: string) =>
      `Bir oylik xarajatlarni darhol to'ladingiz (${amount}), keyingi 2 navbatni o'tkazib yuborasiz va 2 oy kun maoshsiz qolasiz.`,
    immune: "Siz o'z mehnatingiz egasisiz — ishsizlik sizga tahdid qilmaydi.",
    ok: "Qiyin, lekin davom etamiz",
  },
  escape: {
    headline: "Kundalik aylanadan chiqding!",
    sub: "Endi Erkinlik yo'li seniki.",
    cta: "Erkinlik yo'liga o'tish",
    botEscaped: (name: string) => `${name} Kundalik aylanadan chiqdi!`,
  },
  statement: {
    title: "Moliyaviy hisobot",
    tabReport: "Hisobot",
    tabAssets: "Aktivlar",
    tabLog: "Jurnal",
    tabLessons: "Darslar",
    income: "Daromad",
    salarySummary: "Maosh",
    passiveSummary: "Passiv daromad",
    investmentSummary: "Investitsiya daromadi",
    netCashflow: "Sof naqd oqim",
    businessSummary: "Biznes boshqaruvi",
    businessRevenue: "Biznes tushumi",
    businessCosts: "Operatsion xarajat",
    businessNet: "Biznes sof oqimi",
    businessHint: "Tushumdan xodim, ijara, ta'minot va marketing xarajatlari ayriladi.",
    salaryRow: "Ish haqi",
    salaryByQuadrant: {
      E: "Maosh",
      S: "Shaxsiy daromad",
      B: "Biznesdan oylik",
      I: "Kapitaldan daromad",
    } as Record<string, string>,
    unemployedRow: (n: number) => `Ishsiz — ${n} oy qoldi`,
    /** fix-12: avans endi sof maoshdan hisoblanadi (maosh − kredit to'lovlari) */
    avansHint: "💸 Avans: (maosh − kredit to'lovlari) × 30% — kredit puli avansga kirmaydi",
    totalIncome: "Jami daromad",
    incomeHint: "Sof oqim = jami daromad − xarajatlar. Maqsad — passiv daromadni xarajatlarga tenglashtirish.",
    expensesTitle: "Xarajatlar",
    taxes: "Soliqlar",
    housing: "Uy-joy",
    food: "Oziq-ovqat",
    transport: "Transport",
    children: "Farzandlar",
    loanPaymentsRow: "Qarz to'lovlari",
    installmentRow: "Bo'lib to'lash",
    monthsLeft: (n: number) => `${n} oy qoldi`,
    other: "Boshqa",
    totalExpenses: "Jami xarajatlar",
    cashflowTitle: "Oylik naqd oqim",
    cashTitle: "Naqd pul",
    gaugeCaption: "Passiv daromad / Xarajatlar",
    gaugeFT: "Orzu narxiga yaqinlashish",
    assetsTitle: "Aktivlar",
    liabilitiesTitle: "Passivlar",
    emptyAssets: "Hali aktiv yo'q — Imkoniyat katakchalarini qidiring",
    emptyLoans: "Qarzlar yo'q — zo'rsiz!",
    monthlyFlow: "Oylik oqim",
    buyPrice: "Sotib olingan narx",
    marketValue: "Bozor qiymati",
    sellAnytime: "Sotish",
    sellConfirm: "Sotilsinmi?",
    sellConfirmYes: "Ha, sotish",
    sellCancel: "Bekor",
    loanSchedule: "Grafik",
    loanPartial: "Qisman",
    partialAmount: "Summa",
    partialApply: "To'lash",
    paymentRow: "To'lov",
    principal: "Qoldiq qarz",
    paidOff: "To'langan",
    payOff: "To'liq yopish",
    debtLoad: "Qarz yuki",
    debtLoadDanger: "Qarz yuki xavfli!",
    freedomTitle: "Chiqish shartlari",
    stage1: "Moliyaviy xavfsizlik",
    stage2: "Mustaqillik",
    stage3: "Erkinlik",
    stage1Hint: "Naqd ≥ 3× oylik xarajatlar",
    stage2Hint: "Passiv daromad ≥ xarajatlar",
    stage3Hint: "Passiv daromad xarajatlardan 20% ko'p",
    chkStreak: (cur: number, need: number) => `Passiv ≥ xarajatlar ×1,2: ${cur}/${need} ketma-ket oy kun`,
    chkZaxira: "yoki: naqd zaxira ≥ 3× oylik xarajat",
    chkAssets: (cur: number, need: number) => `Aktivlar: ${cur}/${need} ta`,
    chkDebt: (pct: number) => `Qarz yuki ≤ 50%: hozir ${pct}%`,
    quadrantTitle: "Kvadrant yo'li",
    quadrantHintS: "S: biznes aktiv + bilim ≥ 2",
    quadrantHintB: "B: 2+ aktiv + menejer",
    quadrantHintI: "I: portfel ≥ 100 mln",
    quadrantAdvanced: (name: string) => `${name} kvadrantiga ko'tarildi! (+1 bilim)`,
    knowledgeChip: (n: number, max: number) => `Bilim: ${n}/${max}`,
    knowledgeHint: "Ta'lim hodisalari va yangi turdagi bitimlar bilim beradi",
    openKnowledge: "Bilim olish",
    openClients: "Mijoz topish",
    clientsTitle: "Mijozlar",
    clientsEmpty: "Biznes aktiv sotib oling — mijozlar oqim keltiradi",
    /** fix-12: S+ kvadrantda mijoz yo'q bo'lsa birinchi qadam ko'rsatmasi */
    clientsEmptyHint: "🤝 Mijoz topish markazidan birinchi mijozni jalb qiling",
    workOffer: "📋 Ish",
    workOfferTitle: "Ish taklifi: narx fee × 20% · 70% fee +20% (maks 2) / 30% sadoqat −1 · oyda 1 marta",
    workCooldown: "Bu oyda taklif yuborilgan",
    workMaxBoosts: "Maks boost",
    workBoosts: (n: number, max: number) => `boost ${n}/${max}`,
    clientCapNote: (n: number) => `Menejersiz faqat ${n} ta faol mijoz`,
    managerHired: "Menejer faol — mijoz cheklovi yo'q",
    hireManager: "Menejer yollash",
    hireManagerCost: (amount: string) => `Menejer yollash (${amount})`,
    hireManagerHint: "Mijozlar cheklovini oladi · B kvadranti sharti",
    sellForced: "Shoshilinch sotish",
    forcedSellHint:
      "Bankrotlik oldini olish: aktivlar shoshilinch narxda sotiladi (bozor × sotuv koeffitsienti × shoshilinch chegirma)",
    urgentBreakdown: (market: string, resalePct: number, discountPct: number, net: string) =>
      `Bozor: ${market} · Sotuv koeffitsienti: ${resalePct}% · Shoshilinch chegirma: −${discountPct}% = Qo'lga: ${net} so'm`,
    qarzFree: "Foizsiz",
    qarzDue: (month: number) => `Qaytarish: ${month}-oyda`,
    qarzRepay: "Qaytarish",
    navbat: "Navbat",
    escapedBadge: "Erkinlik",
    bankruptBadge: "Bankrot",
    emptyLog: "Jurnal hozircha bo'sh",
    perMonth: "/oy",
    ftCashflowRow: "Erkinlik yo'li oqimi",
    viewStatement: "Hisobotni ko'rish",
  },
  ft: {
    dealTitle: "Yirik biznes",
    buy: "Sotib olish",
    pass: "O'tkazib yuborish",
    cashflowRow: "Oylik oqim",
    cantAfford: "Naqd pul yetarli emas",
    payday: (amount: string) => `Erkinlik yo'li oy kuni: ${amount}`,
    bonus: (amount: string) => `Naqd bonus: ${amount}`,
    audit: (amount: string) => `Soliq auditi: ${amount} to'landingiz`,
    dreamTitle: "Orzu katagi!",
    dreamBuy: (price: string) => `Orzuni sotib olish (${price})`,
    dreamWait: "Hali mablag' yetarli emas — yig'ishda davom eting!",
    dreamUpkeep: (amount: string) => `Oylik saqlash: −${amount}/oy`,
    dreamIncome: (amount: string) => `Orzu + biznes: +${amount}/oy sof daromad`,
    dreamCredit: "Obro': har oy +10 kredit reytingi",
    dreamFree: "Bir martalik — oylik xarajat yo'q",
    dreamHoldRule: "G'alaba sharti: orzuni 3 oy ushlab turish",
    dreamHoldProgress: (n: number, need: number) => `Ushlab turildi: ${n}/${need} oy`,
    dreamBoughtToast: "Orzu sotib olindi! Endi uni 3 oy ushlab turing.",
    dreamUpkeepLog: (title: string, amount: string) => `Orzu xarajati (${title}): −${amount}`,
    dreamIncomeLog: (title: string, amount: string) => `Orzu daromadi (${title}): +${amount} sof`,
    charityBody: "10% naqd pulingizni xayriya qiling — 1 aylana 2 ta zar.",
    winCashflow: "+50 mln/oy Erkinlik yo'li oqimi to'plandi!",
  },
  bankruptcy: {
    title: "Naqd pul tugadi!",
    body: "Majburiy to'lovdan keyin balansingiz manfiy. Chiqish yo'lini tanlang:",
    sellAssets: "Aktiv sotish (shoshilinch narxda)",
    emergencyLoan: "Bankdan shoshilinch qarz (40%/yil, 12 oy)",
    loanUsed: "Shoshilinch qarz allaqachon olingan",
    qarz: "🤝 Qarindoshlardan qarz (foizsiz)",
    qarzHint: "Foizsiz qarz — ishonch. Vaqtida qaytarsangiz, munosabat saqlanadi.",
    qarzAmount: "Summa",
    qarzTerm: "Muddat",
    qarzMonths: (n: number) => `${n} oy`,
    qarzDueInfo: (month: number) => `${month}-oyda to'liq qaytariladi — oylik to'lov yo'q`,
    qarzTake: (amount: string) => `Qarz olish (${amount})`,
    qarzActive: "Faol qarz bor — avval uni qaytaring",
    qarzBlocked: (month: number) => `Ishonch yo'qolgan — ${month}-oygacha qarz berilmaydi`,
    qarzTooSmall: "Minimal summa yetarli emas",
    qarzLate: "Qarzni vaqtida qaytarmadingiz — ishonch yo'qoldi",
    finalTitle: "Bankrot bo'ldingiz",
    finalBody: "Moliyaviy savodxonlik — mashq bilan keladi. Yana urinib ko'ring!",
    spectate: "Kuzatishda davom etish",
    newGame: "Yangi o'yin",
    botBankrupt: (name: string) => `${name} bankrot bo'ldi`,
  },
  /* fix-13b (M1): Moliyaviy ustoz (mentor) */
  mentor: {
    notifTitle: "Moliyaviy ustoz",
    cardTitle: "Moliyaviy ustoz",
    understood: "Tushundim ✓",
    tipLabel: "Maslahat",
    emptyLessons: "Hozircha dars ochilmadi — o'ynang, ustoz har qadamda maslahat beradi",
    learnedCount: (n: number, total: number) => `${n}/${total} dars o'zlashtirildi`,
  },
  end: {
    winTitle: "Moliyaviy erkinlik!",
    winSub: (name: string) => `${name} orzusiga erishdi`,
    dreamWinNote: "Orzu 3 oy davomida saqlandi!",
    botWinSub: (name: string) => `${name} g'olib bo'ldi`,
    bankruptTitle: "O'yin tugadi",
    rounds: "Aylanalar soni",
    assetsBought: "Sotib olingan aktivlar",
    totalPassive: "Jami passiv daromad",
    escapeRound: "Chiqish aylanasi",
    lessonsTitle: "Bu o'yinda o'rgangan darslaringiz",
    noLessons: "Bu o'yinda dars ochilmadi — keyingi safar ustoz ko'proq maslahat beradi",
    newGame: "Yangi o'yin",
    home: "Bosh sahifa",
  },
  /* Bilim olish + Mijoz topish markazlari (fix-9) */
  actions: {
    knowledgeTitle: "Bilim olish markazi",
    knowledgeSub: "Bilim darajangizni oshiring — bilim talab qiluvchi bitimlar va yangi kvadrantlar ochiladi",
    knowledgeNow: (n: number, max: number) => `Hozirgi bilim: ${n}/${max}`,
    clientsTitle: "Mijoz topish markazi",
    clientsSub: "Marketing kanallari orqali biznesingizga yangi mijozlar olib keling",
    clientsLocked: "S kvadrantiga o'ting",
    clientsNow: (active: number, total: number) => `Mijozlar: ${active} faol / ${total} jami`,
    capNote: (n: number) => `Menejersiz bandlik: faqat ${n} tasi to'laydi (qolganlari navbatda kutadi)`,
    managerActive: "Menejer faol — mijoz cheklovi yo'q",
    use: "Boshlash",
    cooldownNote: (n: number) => `${n} oydan keyin yana`,
    noCash: "Naqd yetarli emas",
    maxKnowledge: "Maksimal bilim darajasi",
    noClients: "Kamida 1 mijoz kerak",
    costLabel: "Narx",
    perClient: "har mijoz uchun",
    /** fix-12: eng yaxshi arzon kanal belgisi */
    recommended: "Tavsiya",
    knowledge: {
      book: {
        title: "Kitob o'qish",
        desc: "Moliyaviy savodxonlik kitobi — arzon va ishonchli usul",
        effect: "+1 bilim (kafolatlangan) · 2 oyda bir marta",
      },
      webinar: {
        title: "Vebinar",
        desc: "Onlayn jonli dars — omadli bo'lsa tez natija",
        effect: "60% ehtimol bilan +1 bilim · har oy",
      },
      course: {
        title: "Onlayn kurs",
        desc: "Tizimli video kurs — sertifikat bilan",
        effect: "+1 bilim (kafolatlangan) · 2 oyda bir marta",
      },
      seminar: {
        title: "Biznes seminar",
        desc: "Tadbir + networking: S/B/I kvadrantda mijoz ham topilishi mumkin",
        effect: "+1 bilim + 50% ehtimol bilan +1 mijoz · 3 oyda bir marta",
      },
    },
    clients: {
      instagram: {
        title: "Instagram reklama",
        desc: "Maqsadli auditoriyaga vizual reklama",
        effect: "65% ehtimol bilan +1 mijoz (0,8–1,5 mln/oy) · har oy",
        expect: "Kutilma: +1 mijoz, 0,8–1,5 mln/oy · 65%",
      },
      telegram: {
        title: "Telegram targ'ibot",
        desc: "Mahalliy kanallarda reklama posti",
        effect: "50% ehtimol bilan +1 mijoz (0,5–1 mln/oy) · har oy",
        expect: "Kutilma: +1 mijoz, 0,5–1 mln/oy · 50%",
      },
      referal: {
        title: "Referal dasturi",
        desc: "Mavjud mijozlaringiz do'stlarini taklif qiladi",
        effect: "Har mijoz 40% ehtimol bilan +1 yangi (maks 3) · 2 oyda bir marta",
        expect: "Kutilma: har mijozdan 40% · maks +3 yangi",
      },
      networking: {
        title: "Networking tadbir",
        desc: "Biznes-forum va uchrashuvlar — ishonchli kontaktlar",
        effect: "Kafolatlangan +1 mijoz (1–2 mln/oy) + 25% yana +1 · 2 oyda bir marta",
        expect: "Kutilma: kafolatlangan +1 (25% yana +1), 1–2 mln/oy",
      },
      promo: {
        title: "Mahalliy akciya/chegirma",
        desc: "Chegirmalar tez mijoz keltiradi, lekin sadoqat pasayadi",
        effect: "+2 mijoz (0,4–0,8 mln/oy), mavjud mijozlar sadoqati −1 · 3 oyda bir marta",
        expect: "Kutilma: +2 mijoz (0,4–0,8 mln/oy), sadoqat −1",
      },
    },
  },
  toasts: {
    dealSigned: "Bitim imzolandi!",
    notEnoughCash: "Naqd pul yetarli emas",
    loanPaidOff: "Qarz to'liq yopildi!",
    qarzTaken: "🤝 Foizsiz qarz olindi — vaqtida qaytaring!",
    loanClosed: (name: string, monthly: string) =>
      `🎉 KREDIT TO'LIQ YOPILDI: ${name}. Oylik ${monthly} endi xarajatlardan olib tashlandi!`,
    soldAnytime: (net: string, market: string) => `Sotildi: +${net} so'm (bozor: ${market})`,
    partialPaid: (amount: string) => `Qisman to'lov: −${amount}`,
    deferReturned: (amount: string) => `Kechiktirgan xarajatingiz qaytdi: −${amount} (narx +12%)`,
    salaryIndexed: (name: string, amount: string) => `${name}: maosh indeksatsiyasi +6% → ${amount}`,
    quadrantAdvanced: (name: string, quadrant: string) => `${name} ${quadrant} kvadrantiga ko'tarildi!`,
    managerHired: (amount: string) => `Menejer yollandi: −${amount} (mijoz cheklovi olib tashlandi)`,
    clientsJoined: (n: number) => `${n} ta yangi mijoz qo'shildi`,
    saved: "O'yin saqlandi",
  },
} as const;
