/**
 * Central Uzbek (Latin) strings dictionary (design.md §10).
 * All UI copy MUST come from here — zero hard-coded strings in components.
 */
export const uz = {
  app: {
    name: "OQIM",
    fullTitle: "OQIM — Moliyaviy erkinlik o'yini",
    tagline: "Aylanadan chiq!",
    disclaimer: "Ta'limiy o'yin, investitsiya maslahati emas",
    copyright: "© 2025 OQIM · Toshkent",
    version: "v1.0",
    whatsNewTitle: (v: number) => `✨ Yangi versiya v${v}`,
    whatsNewSub: "Bu versiyada nimalar o'zgardi:",
    whatsNewClose: "Tushundim",
  },
  nav: {
    home: "Bosh sahifa",
    game: "O'yin",
    rules: "Qoidalar",
    profile: "Profil",
    play: "O'ynash",
    resume: "Davom etish",
    menu: "Menyu",
    close: "Yopish",
  },
  footer: {
    pages: "Sahifalar",
    about: "O'yin haqida",
    aboutText: "Moliyaviy savodxonlik o'yini — O'zbekiston uchun 🇺🇿",
    contact: "Aloqa",
  },
  common: {
    start: "O'yinni boshlash",
    learnRules: "Qoidalarni o'rganish",
    rulesAndGlossary: "Qoidalar va lug'at",
    salary: "Maosh",
    expenses: "Xarajatlar",
    savings: "Jamg'arma",
    monthlyCashflow: "Oylik naqd oqim",
    debts: "Qarzlar",
    passiveIncome: "Passiv daromad",
    cash: "Naqd",
    price: "Narx",
    capitalGrowth: "Kapital o'sish",
    perMonth: "/oy",
    perYear: "/yil",
    turn: "Navbat",
    rollDice: "Zar tashlash",
    newGame: "Yangi o'yin",
    continueGame: "Davom etish",
    win: "G'alaba!",
  },
  cells: {
    opportunity: { name: "Imkoniyat", desc: "Kichik yoki katta bitim kartasini torting" },
    market: { name: "Bozor", desc: "Bozor hodisasi — aktivlarni sotish imkoniyati" },
    event: { name: "Hodisa", desc: "Hayotiy hodisa: ba'zan xarajat, ba'zan omad" },
    charity: { name: "Xayriya", desc: "Ixtiyoriy ehson — keyingi yurishda bonus" },
    doodad: { name: "Kutilmagan xarajat", desc: "Cho'ntakni bo'shatuvchi xarajat" },
    payday: { name: "Oy kun", desc: "Maosh kuni — oylik naqd oqimni oling" },
    baby: { name: "Farzand tug'ildi", desc: "Oila kengaydi — xarajatlar oshadi" },
    downsized: { name: "Ishsizlik", desc: "Ikki yurish o'tkazib yuborasiz" },
  },
  home: {
    eyebrow: "O'ZBEKISTON UCHUN MOSLASHTIRILGAN MOLIYAVIY O'YIN",
    heroTitleA: "Aylanadan chiq!",
    heroTitleB: "Moliyaviy erkinlikni",
    heroTitleC: "o'yin orqali o'rgan.",
    heroSub:
      "Kasblar, narxlar, investitsiyalar va hodisalar butunlay o'zbekcha. Oylik 3,5 mln so'mdan boshlang, passiv daromading xarajatlardan oshguncha kurash — Kundalik aylanadan chiq!",
    trust: "Yakka yoki jamoaviy ✦ Brauzerda saqlanadi ✦ 2–4 o'yinchi (botlar bilan)",
    luckToast: (n: number) => `Demak, bugun omading: ${n}!`,
    stats: [
      { value: 10, suffix: "", label: "Haqiqiy o'zbek kasblari" },
      { value: 40, suffix: "+", label: "Investitsiya bitimlari" },
      { value: 30, suffix: "+", label: "Hodisalar va bozor kortlari" },
      { value: 30, suffix: "", label: "Kundalik aylana kataklari" },
    ],
    how: {
      eyebrow: "O'YIN MEXANIKASI",
      title: "Uch qadam — bir maqsad",
      steps: [
        {
          num: "01",
          title: "Kasbingni ol",
          body: "Har o'yinchi tasodifiy kasb oladi: maktab o'qituvchisi, taksi haydovchi yoki dasturchi. Maosh, xarajatlar va qarzlar — hammasi O'zbekiston realiyasidan.",
        },
        {
          num: "02",
          title: "Zar tashla, harakatlan",
          body: "Doskada Imkoniyat, Bozor, Hodisa va Xayriya kataklari seni kutadi. Bitimlar tuz, kvartira sotib ol, to'y takliflaridan qoch.",
        },
        {
          num: "03",
          title: "Passiv daromadni oshir",
          body: "Oylik passiv daromading jami xarajatlardan oshgan zahoti — Kundalik aylana tugadi. Erkinlik yo'lida katta bizneslar va orzular kutmoqda.",
        },
      ],
    },
    rings: {
      title: "Ikki olam — bitta o'yin",
      sub: "Kichkina aylanada omon qolish kurashi. Katta aylanada orzular sotib olinadi.",
      ratRace: "Kundalik aylana",
      ratRaceCaption: "Omon qolish sikli",
      fastTrack: "Erkinlik yo'li",
      fastTrackCaption: "Passiv daromad ≥ Xarajatlar",
      dream: "Orzu",
      exitCondition: "Chiqish sharti",
      yourPassive: "Passiv daromading",
      expensesFixed: "Xarajatlar",
      congrats: "Tabriklaymiz! Bu — o'yindagi g'alaba sharti.",
    },
    professions: {
      title: "Kim bo'lib boshlaysan?",
      sub: "10 ta kasb — 10 ta turli start. Hammasi real o'zbek bozoridan olingan raqamlar.",
      stamp: "TANLASH MUMKUN",
    },
    investments: {
      title: "Nimaga investitsiya qilasan?",
      sub: "Choyxonadan IPOgacha — o'zbek iqtisodiyotining haqiqiy instrumentlari.",
      tabs: {
        all: "Barchasi",
        realestate: "Ko'chmas mulk",
        business: "Kichik biznes",
        securities: "Qimmatli qog'ozlar",
        currency: "Valyuta",
      },
      riskPrefix: "Risk:",
    },
    events: {
      title: "Hayot aralashadi",
      sub: "30+ hodisa kartasi — ba'zisi cho'ntakni bo'shatadi, ba'zisi yo'l ochadi.",
    },
    academy: {
      eyebrow: "O'QUV BO'LIMI",
      title: "Faqat o'yin emas — moliyaviy maktab",
      body: "Aktiv va passiv farqini, naqd oqimni, ROI ni, ipoteka mexanikasini — barchasini Qoidalar sahifasida sodda o'zbek tilida tushuntiramiz. O'yin o'ynagancha o'z hisobotingni o'qishni o'rganasan.",
      checklist: [
        "Moliyaviy hisobotni o'qish",
        "Passiv daromad strategiyalari",
        "O'zbekiston konteksti: subsidiya, ipoteka, inflyatsiya",
      ],
    },
    cta: {
      title: "Orzular Erkinlik yo'lida kutmoqda.",
      sub: "Bitta zar — va o'yin boshlanadi. Bugun qaysi kasb omad keltiradi?",
      start: "O'yinni boshlash",
      rules: "Qoidalar",
    },
  },
  auth: {
    title: "Akkaunt",
    subtitle: "Profil ma'lumotlaringizni bulutga saqlash uchun kiring yoki ro'yxatdan o'ting",
    loginTab: "Kirish",
    registerTab: "Ro'yxatdan o'tish",
    email: "Email",
    password: "Parol",
    name: "Ismingiz",
    loginButton: "Kirish",
    registerButton: "Ro'yxatdan o'tish",
    logoutButton: "Chiqish",
    loggedInAs: (name: string) => `Tizimga kirdingiz: ${name}`,
    syncButton: "Bulutga saqlash",
    syncSuccess: "Profil bulutga saqlandi",
    syncError: "Sinxronlashda xato",
    mergeButton: "Bulutdan yuklash",
    mergeSuccess: "Bulutdagi ma'lumotlar yuklandi",
    emailRequired: "Email kiriting",
    passwordRequired: "Parol kiriting",
    nameRequired: "Ismingizni kiriting",
    invalidEmail: "Email noto'g'ri",
    passwordMin: "Parol kamida 6 ta belgi",
    loginError: "Email yoki parol noto'g'ri",
    registerError: "Ro'yxatdan o'tishda xato",
    accountExists: "Bu email bilan ro'yxatdan o'tilgan",
    playRequired: "O'yinni boshlash uchun tizimga kiring yoki ro'yxatdan o'ting.",
    backHome: "Bosh sahifaga qaytish",
  },
  profile: {
    title: "Profil",
    sub: "O'yinlaringiz tarixi, statistika va yutuqlar",
    statsTitle: "Umumiy statistika",
    games: "O'yinlar soni",
    winPct: "G'alaba foizi",
    fastestEscape: "Eng tez escape",
    fastestEscapeUnit: (n: number) => `${n}-oy`,
    maxPassive: "Eng yuqori passiv daromad",
    recentTitle: "So'nggi o'yinlar",
    empty: "Hali o'yinlar yo'q — birinchi o'yiningizni boshlang!",
    playNow: "O'ynash",
    thDate: "Sana",
    thHero: "Qahramon",
    thResult: "Natija",
    thMonth: "Oy",
    thQuadrant: "Kvadrant",
    resultWin: "G'alaba",
    resultEscape: "Chiqdi",
    resultLoss: "Yakun",
    achievementsTitle: "Yutuqlar",
    locked: "Yopiq",
    lessonsTitle: "Moliyaviy savodxonlik",
    lessonsProgress: (n: number, total: number) => `Moliyaviy savodxonlik: ${n}/${total} dars o'zlashtirildi`,
    lessonsEmpty: "O'yinlarda Moliyaviy ustoz darslarini oching — ular shu yerda to'planadi",
    clearTitle: "Ma'lumotlarni tozalash",
    clearConfirm: "Rostdan ham barcha statistikani o'chirasizmi?",
    clearYes: "Ha, tozalash",
    clearCancel: "Bekor qilish",
  },
  game: {
    placeholderTitle: "O'yin sahifasi",
    placeholderBody: "Bu sahifa tez orada tayyor bo'ladi — doska, zarlar va moliyaviy hisobot shu yerda yashaydi.",
  },
  rules: {
    placeholderTitle: "Qoidalar sahifasi",
    placeholderBody: "O'yin qoidalari va moliyaviy savodxonlik akademiyasi tez orada shu yerda bo'ladi.",
  },
} as const;

export type UzDictionary = typeof uz;
