import {useEffect, useRef, useState} from 'react';
import {Link} from 'react-router';
import {ArrowRight, BookOpen, Check, ChevronRight, Heart, MapPin, RotateCcw, TrendingUp, Wallet} from 'lucide-react';
import {Dialog, DialogContent, DialogTitle, DialogDescription} from '@/components/ui/dialog';
import {act, economics, EVENTS, finances, makeBusiness, money, quote, readSave, ROLES, SAVE_KEY, SECTORS, start} from './engine';
import type {Action, Place, Role, Sector, State} from './engine';
import './life.css';
import TownMap from './TownMap';
import BusinessInterior from './BusinessInterior';
import {places} from './places';

function Scene({index}:{index:number}) {return <div className="life-scene" aria-hidden="true"><img src="/event-scenes.webp" alt="" style={{left:`-${(index%4)*100}%`,transform:`translateY(-${(Math.floor(index/4)+.5)*100/3}%)`}}/></div>;}
function signed(n:number){return `${n>=0?'+':'−'}${money(Math.abs(n))}`;}
function initial(){try{return readSave(localStorage.getItem(SAVE_KEY));}catch{return null;}}
export default function LifeGame(){
  const [state,setState]=useState<State|null>(initial);
  const [place,setPlace]=useState<Place>('home');
  const [tab,setTab]=useState<'map'|'report'|'journal'>('map');
  const [confirm,setConfirm]=useState<Action|null>(null);
  const [reset,setReset]=useState(false);
  const [help,setHelp]=useState(false);
  const [saveError,setSaveError]=useState(false);
  const [walking,setWalking]=useState(false);
  const [interior,setInterior]=useState(false);
  const [offer,setOffer]=useState<Sector>('trade');
  const decisionRef=useRef<HTMLElement>(null);
  function changeTab(next:'map'|'report'|'journal'){setTab(next);requestAnimationFrame(()=>document.querySelector('.life-workspace')?.scrollIntoView({behavior:'instant',block:'start'}));}
  function choosePlace(next:Place){setInterior(false);setPlace(next);if(window.matchMedia('(max-width: 860px)').matches)decisionRef.current?.scrollIntoView({behavior:'instant',block:'start'});}
  useEffect(()=>{if(!state)return;let failed=false;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{failed=true;}const timer=setTimeout(()=>setSaveError(failed),0);return()=>clearTimeout(timer);},[state]);
  function begin(role:Role){setState(start(role));setPlace(role==='owner'?'market':role==='freelancer'?'studio':'office');setHelp(true);}
  function run(a:Action){setState(s=>s?act(s,a):s);setConfirm(null);}
  if(!state)return <div className="life-game life-start"><header className="life-top"><Link to="/" className="life-brand">OQIM<span>HAYOT</span></Link><Link to="/game">Avvalgi o‘yin</Link></header><main>
    <div className="life-start-title"><span className="life-eyebrow">YANGI HAYOT. SIZNING QARORLARINGIZ.</span><h1>Shaharchadagi hikoyangiz<br/>qayerdan boshlanadi?</h1><p>Ishlang, biznes quring, hayotga vaqt ajrating.<br/>Maqsad — xarajatlaringizni qoplaydigan mustaqil daromad.</p></div>
    <div className="life-roles">{(Object.keys(ROLES) as Role[]).map(role=><button key={role} className="life-role" onClick={()=>begin(role)}><img src={ROLES[role].image} alt=""/><h2>{ROLES[role].title}</h2><p>{ROLES[role].description}</p><dl><div><dt>Naqd zaxira</dt><dd>{money(ROLES[role].cash)} so‘m</dd></div><div><dt>Oylik yashash</dt><dd>{money(ROLES[role].living)} so‘m</dd></div></dl><span className="life-primary">Shu hayotni boshlash <ArrowRight size={18}/></span></button>)}</div>
    <p className="life-disclosure">Bir oy — 4 ta haftalik qaror. Hisob-kitoblar o‘quv simulyatsiyasi; narxlar jonli bozor ma’lumotlari emas. Jarayon shu qurilmada saqlanadi.</p>
  </main></div>;
  const s=state,f=finances(s),location=places.find(p=>p.id===place)!;
  const offers=(Object.keys(SECTORS) as Sector[]).filter(k=>SECTORS[k].place===place);
  const selectedSector=offers.includes(offer)?offer:offers[0];
  const business=s.businesses.find(b=>b.sector===selectedSector);
  const event=s.event?EVENTS[s.event]:null;
  const goal=Math.min(100,Math.max(0,Math.round(f.passive/Math.max(1,f.expense)*100)));
  function action(a:Action,detail:string,important=false){const q=quote(s,a);if(walking)q.reason='Qahramon yetib kelishini kuting.';return <div className="life-action"><button disabled={!!q.reason} onClick={()=>important?setConfirm(a):run(a)}><span>{q.label}<small>{detail}</small></span><ChevronRight size={20}/></button>{q.reason&&<small className="life-disabled-reason">{q.reason}</small>}</div>;}
  const activeOwned=(p:Place)=>s.businesses.some(b=>SECTORS[b.sector].place===p)||(p==='bank'&&s.rentals>0);
  return <div className="life-game">
    <header className="life-top"><Link to="/" className="life-brand">OQIM<span>HAYOT</span></Link><div className="life-calendar"><span>{s.month}-oy</span><strong>{s.actions} ta hafta qoldi</strong></div><div className="life-top-actions"><button onClick={()=>setHelp(true)} aria-label="O‘yin yo‘riqnomasi"><BookOpen size={19}/></button><button onClick={()=>setReset(true)} aria-label="Yangi hayot boshlash"><RotateCcw size={19}/></button><Link to="/game">Avvalgi o‘yin</Link></div></header>
    {saveError&&<p role="alert" className="life-alert">O‘yin saqlanmadi. Brauzer xotirasida joy yetishmasligi mumkin. Bu oynani yopmang.</p>}
    <div className="life-shell">
      <nav className="life-nav" aria-label="O‘yin bo‘limlari"><img src={ROLES[s.role].image} alt={ROLES[s.role].title}/>{([{id:'map',name:'Shaharcha',icon:MapPin},{id:'report',name:'Hisobot',icon:Wallet},{id:'journal',name:'Kundalik',icon:BookOpen}] as const).map(t=><button key={t.id} aria-current={tab===t.id?'page':undefined} onClick={()=>changeTab(t.id)}><t.icon size={23}/><span>{t.name}</span></button>)}<div className="life-energy"><Heart size={18}/><strong>{s.energy}%</strong><span>Quvvat</span></div></nav>
      <main className="life-workspace">
        <div className="life-stats"><div><span><Wallet size={16}/> Naqd pul</span><strong>{money(s.cash)} <small>so‘m</small></strong></div><div><span><TrendingUp size={16}/> Oylik sof oqim</span><strong className={f.flow<0?'life-negative':'life-positive'}>{signed(f.flow)}</strong></div><div><span>Passiv daromad</span><strong>{money(f.passive)}</strong></div><div><span>Qarz qoldig‘i</span><strong>{money(s.loan?.principal??0)}</strong></div></div>
        {tab==='map'?<>
          <div className="life-map-heading"><div><span className="life-eyebrow">MENING SHAHARCHAM</span><h1>Bugun qaysi imkoniyatni tanlaysiz?</h1></div><span className="life-market-weather">Bozor talabi: {s.demand}%</span></div>
          {interior&&selectedSector?<BusinessInterior key={selectedSector} state={s} sector={selectedSector} onBack={()=>setInterior(false)}/>:<TownMap place={place} onArrive={choosePlace} onWalking={setWalking} owned={activeOwned}/>}
          <div className="life-week"><div><strong>{s.actions===0?'Oy yakuniga tayyorsiz':'Bir hafta — bitta mazmunli qaror'}</strong><span>{s.actions===0?'Daromadlar va xarajatlar endi hisoblanadi.':'Ish, biznes, bilim yoki dam olishdan birini tanlang.'}</span></div><button className="life-primary" disabled={walking||!!quote(s,{type:'month'}).reason} onClick={()=>setConfirm({type:'month'})}>Oyni yakunlash <ArrowRight size={18}/></button></div>
        </>:tab==='report'?<section className="life-report"><h1>Pulingiz qayerdan keladi?</h1><p>Quyidagi hisob — joriy talab va quvvat bo‘yicha shu oy uchun prognoz. Yetmagan zaxira avtomatik xarid qilinadi; xarid pul oqimida, ishlatilgan zaxira tannarxda hisoblanadi.</p><dl className="life-ledger">{[['Maosh',s.salary],['Biznesdan sof foyda',f.business],['Ijara daromadi',f.rent],['Jami sof daromad',f.income],['Amortizatsiya (naqd emas)',f.depreciation],['Ombordan ishlatilgan zaxira',f.inventoryRelease],['Debitorlik o‘zgarishi',-f.receivableChange],['Kreditorlik o‘zgarishi',f.payableChange],['Yashash xarajatlari',-s.living],['Kredit foizi',-f.interest],['Kredit asosiy to‘lovi',-f.repayment],['Sof naqd oqim',f.flow]].map(([label,value])=><div key={label}><dt>{label}</dt><dd className={Number(value)<0?'life-negative':''}>{signed(Number(value))} so‘m</dd></div>)}</dl>
          <h2>Bizneslaringiz ichida</h2>{s.businesses.length===0?<p>Hali biznesingiz yo‘q. Shaharchadan birinchi imkoniyatni tanlang.</p>:s.businesses.map(b=>{const e=economics(s,b),d=SECTORS[b.sector];return <article className="life-business-report" key={b.sector}><h3>{d.name} <small>{b.manager?'Boshqaruvchi bilan':'O‘zingiz boshqarasiz'}</small></h3><p>{e.units} / {e.capacity} {d.unit} · {b.level}-bosqich</p><p>Zararsizlik: {e.breakEven===null?'erishilmaydi':`${e.breakEven} ${d.unit}`} · sof marja {e.margin.toFixed(1)}%</p><dl className="life-ledger">{[['Tushum',e.revenue],[d.input,-e.variable],['Ijara',-e.rent],['Ishchilar maoshi',-e.wages],['Kommunal va xizmat',-e.other],['Boshqaruvchi',-e.manager],['Model solig‘i (4%)',-e.tax],['Amortizatsiya',-e.depreciation],['Sof foyda',e.profit],['Mijozlardan tushgan pul',e.receipts],['Yetkazuvchiga to‘lov',-e.supplierPayment],['Biznes pul oqimi',e.cashFlow],['Ombor qiymati',b.stockValue],['Joriy mijoz qarzi',b.receivable],['Oy oxirida mijoz qarzi',e.receivable],['Joriy yetkazuvchi qarzi',b.payable],['Oy oxirida yetkazuvchi qarzi',e.payable],['Oy oxirida ombor',e.stockValueAfter]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{signed(Number(value))}</dd></div>)}</dl></article>;})}<p className="life-disclosure">O‘quv modeli: aylanma solig‘i 4%, oylik xarajat inflyatsiyasi 0,5%, uskuna muddati 60 oy. Bular amaldagi qonuniy stavkalar emas. Mijoz va yetkazuvchi qarzlari keyingi oy yopiladi. QQS va to‘lovdan butunlay bosh tortish hozir hisoblanmaydi.</p></section>:<section className="life-report"><h1>Qarorlaringiz kundaligi</h1><p>Har bir tanlov va uning pulga ta’siri saqlanadi.</p>{s.log.map((e,i)=><article className="life-log" key={i}><span>{e.month}-oy</span><div><strong>{e.text}</strong>{e.amount!==undefined&&<p className={e.amount<0?'life-negative':'life-positive'}>{signed(e.amount)} so‘m</p>}</div></article>)}</section>}
      </main>
      <aside ref={decisionRef} className="life-side" aria-label="Qarorlar va maqsad">
        <div className="life-goal"><span className="life-eyebrow">MOLIYAVIY MUSTAQILLIK</span><div><h2>{goal}%</h2><span>{s.freedomMonths}/3 oy tasdiqlandi</span></div><progress value={goal} max={100} aria-label="Passiv daromadning xarajatlarni qoplashi"/><p>Passiv daromad xarajatlarni qoplasin. 3 oylik zaxirani saqlab, shu holatni 3 oy davom ettiring.</p></div>
        <section className="life-decision" aria-live="polite">
          <Scene index={event?event.scene:place==='home'?8:place==='office'?0:place==='bank'?2:place==='school'?4:selectedSector?SECTORS[selectedSector].scene:3}/>
          <div className="life-decision-body">{offers.length>0&&!event&&<label className="life-offer-select">Biznes taklifini tanlang<select value={selectedSector} onChange={e=>setOffer(e.target.value as Sector)}>{offers.map(k=><option key={k} value={k}>{SECTORS[k].name}{s.businesses.some(b=>b.sector===k)?' · sizniki':''}</option>)}</select></label>}<span className="life-eyebrow">{event?'HAYOTIY VOQEA':location.hint.toLocaleUpperCase()}</span><h2>{event?event.title:selectedSector?SECTORS[selectedSector].name:location.name}</h2>
            {event?<><p>{event.body}</p>{s.eventTarget&&<p><strong>Ta’sir qiladigan biznes: {SECTORS[s.eventTarget].name}</strong></p>}{event.choices.map((c,i)=><div key={c.label}>{action({type:'event',choice:i},c.detail)}</div>)}</>:<>
              {place==='home'&&<><p>Quvvatingiz 25% dan tushsa, o‘zingiz boshqaradigan biznes unumdorligi 35% kamayadi.</p>{action({type:'rest'},'Quvvat +30 · bepul · 1 hafta')}</>}
              {place==='office'&&<><p>{s.salary?`Maoshingiz oyiga ${money(s.salary)} so‘m. Qo‘shimcha ish zaxirani oshiradi.`:'Biznesdan tashqari bir martalik ish olib, naqd zaxirangizni oshiring.'}</p>{action({type:'work'},'Naqd +600 000 · quvvat −15 · 1 hafta')}</>}
              {place==='school'&&<><p>O‘rgangan bilim xarajatni kamaytiradigan biznes yaxshilanishlarini ochadi.</p><div className="life-inline-stat">Malaka <strong>{s.skill}/5</strong></div>{action({type:'learn'},`${s.role==='employee'?'Maosh +250 000/oy · ':''}Naqd −400 000 · 1 hafta`)}</>}
              {place==='bank'&&<><p>Qarz — daromad emas. Qaytarish imkoniyatingizni hisoblang.</p>{action({type:'loan'},'12 oy · qoldiq qarzga oyiga 2% foiz',true)}{s.loan&&action({type:'repay'},`${money(s.loan.principal)} so‘m · foizlar to‘xtaydi`,true)}{action({type:'rent'},'Narxi 28 mln · sof ijara 1,4 mln/oy',true)}</>}
              {selectedSector&&<><button className="life-primary life-enter-business" disabled={walking} onClick={()=>{setInterior(true);changeTab('map');}}>Biznes ichiga kirish <ArrowRight size={18}/></button>{business?<><div className="life-inline-stat">Oylik sof foyda <strong>{signed(economics(s,business).profit)}</strong></div><p>{business.manager?'Boshqaruvchi ishlayapti. Naqd oqim bilan qoplangan foyda passiv daromadga kiradi.':'Biznesni o‘zingiz boshqarasiz. Foyda hali passiv daromad emas.'}</p>{action({type:'market',sector:selectedSector},'500 000 so‘m · shu oy talab +20%')}{action({type:'expand',sector:selectedSector},`${money(Math.round(SECTORS[selectedSector].price*.4))} so‘m · quvvat +45%`,true)}{action({type:'manager',sector:selectedSector},`${money(SECTORS[selectedSector].manager)} so‘m/oy · passiv boshqaruv`,true)}{action({type:'improve',sector:selectedSector},'800 000 so‘m · o‘zgaruvchan tannarx −4%')}{action({type:'price',sector:selectedSector},'Narx +5% · talab −5% · 1 hafta')}{action({type:'sell',sector:selectedSector},'Qoldiq aktivning 65% + mijoz qarzi − yetkazuvchi qarzi',true)}</>:<><p>{SECTORS[selectedSector].group==='trade'?'Tovarni ulgurji olib, chakana sotasiz. Asosiy xarajat — tovar va ishchilar.':SECTORS[selectedSector].group==='production'?'Xomashyo tayyor mahsulotga aylanadi. Quvvat, ish haqi va energiya foydaga ta’sir qiladi.':'Mijozlarga xizmat sotasiz. Buyurtmalar jamoangizning vaqtiga bog‘liq.'}</p><div className="life-inline-stat">Sotib olish <strong>{money(SECTORS[selectedSector].price)}</strong></div><div className="life-inline-stat">Joriy foyda prognozi <strong>{signed(economics(s,makeBusiness(selectedSector)).profit)}/oy</strong></div>{action({type:'buy',sector:selectedSector},'Biznes sizning aktivingizga aylanadi · 1 hafta',true)}</>}</>}
            </>}
          </div>
        </section>
        <p className="life-tip"><BookOpen size={18}/><span>{f.flow<0?'Xarajat daromaddan yuqori. Yangi majburiyat olishdan oldin oqimni yaxshilang.':s.cash<f.expense*3?'Avval uch oylik xarajatga yetadigan naqd zaxira yarating.':'Zaxirangiz bor. Endi egasiz ham daromad keltiradigan aktivlarni ko‘rib chiqing.'}</span></p>
      </aside>
    </div>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="life-dialog"><DialogTitle>Shaharchadagi ilk qadamlar</DialogTitle><DialogDescription>1 oy = 4 hafta. Har bir amal bir haftani oladi; hayotiy voqea qarorlari qo‘shimcha hafta sarflamaydi.</DialogDescription><ol><li><strong>Binoni tanlang.</strong> Ish, biznes, bank yoki bilim markazini oching.</li><li><strong>Natijani ko‘rib qaror qiling.</strong> Pul va quvvatga ta’sir oldindan yozilgan.</li><li><strong>Oy yakunini kuzating.</strong> Hisobotda tushum, foyda va qarz alohida.</li></ol><p>Aktiv — daromad keltiradigan mulk. Passiv daromad — doimiy mehnatingizsiz keladigan sof daromad.</p><button className="life-primary" onClick={()=>setHelp(false)}>Boshlaymiz <ArrowRight size={18}/></button></DialogContent></Dialog>
    <Dialog open={confirm!==null} onOpenChange={open=>{if(!open)setConfirm(null);}}><DialogContent className="life-dialog"><DialogTitle>{confirm?quote(s,confirm).label:'Qarorni tasdiqlash'}</DialogTitle><DialogDescription>Qaroringizning pulga ta’sirini tekshiring.</DialogDescription>{confirm&&<><dl className="life-ledger"><div><dt>Hozirgi naqd</dt><dd>{money(s.cash)}</dd></div><div><dt>Qarordan keyin</dt><dd>{money(confirm.type==='month'?s.cash+f.flow:s.cash-quote(s,confirm).cost)}</dd></div><div><dt>{confirm.type==='month'?'Shu oy sof oqimi':'Yangi oylik oqim prognozi'}</dt><dd>{signed(confirm.type==='month'?f.flow:finances(act(s,confirm)).flow)}</dd></div></dl>{confirm.type==='month'&&s.cash+f.flow<0&&<p className="life-negative">Oy xarajatlarini qoplashga pul yetmaydi. Tasdiqlasangiz o‘yin tugaydi.</p>}{confirm.type==='loan'&&<p>10 mln so‘m daromad emas, qarzdir. Birinchi oy to‘lovi: 1 033 334 so‘m. To‘lovlar qoldiq kamayishi bilan pasayadi.</p>}<button className="life-primary" disabled={!!quote(s,confirm).reason} onClick={()=>run(confirm)}>Tasdiqlash <Check size={18}/></button><button className="life-secondary" onClick={()=>setConfirm(null)}>Ortga qaytish</button></>}</DialogContent></Dialog>
    <Dialog open={reset} onOpenChange={setReset}><DialogContent className="life-dialog"><DialogTitle>Yangi hayot boshlaysizmi?</DialogTitle><DialogDescription>Faqat ushbu yangi o‘yindagi jarayon o‘chadi. Avvalgi OQIM saqlanmalari o‘zgarmaydi.</DialogDescription><button className="life-primary" onClick={()=>{try{localStorage.removeItem(SAVE_KEY);}catch{/* new game remains playable in memory */}setState(null);setReset(false);}}>Yangidan boshlash</button><button className="life-secondary" onClick={()=>setReset(false)}>Bekor qilish</button></DialogContent></Dialog>
    <Dialog open={s.status!=='playing'}><DialogContent className="life-dialog" onEscapeKeyDown={e=>e.preventDefault()} onInteractOutside={e=>e.preventDefault()}><DialogTitle>{s.status==='won'?'Moliyaviy mustaqillikka erishdingiz!':'Naqd zaxira tugadi'}</DialogTitle><DialogDescription>{s.status==='won'?'Passiv daromad xarajatlarni 3 oy qopladi va zaxirangiz saqlandi.':'Oy yakunida xarajatlarni qoplashga mablag‘ yetmadi. Keyingi urinishda zaxira va oylik oqimga e’tibor bering.'}</DialogDescription><p>{s.month-1} oy · {s.businesses.length+s.rentals} aktiv · {money(s.cash)} so‘m</p><button className="life-primary" onClick={()=>{try{localStorage.removeItem(SAVE_KEY);}catch{/* no persistence available */}setState(null);}}>Yangi hayot</button></DialogContent></Dialog>
  </div>;
}
