import assert from "node:assert/strict";
import { makePlayer, makeGame, applyEvent, applyPayday, eligibleEvents, financeSummary } from "../src/lib/game/engine";
import { operateBusiness, businessStage, advanceBusinessMonth, validBusinessOperations } from "../src/lib/game/business";
import { PROFESSIONS } from "../src/lib/game/data";
import { loadSave, saveGame } from "../src/lib/game/save";
import { SAVE_KEY } from "../src/lib/game/types";
// Legacy save contract: existing balances and orders must keep their old economics.
const make = () => {
  const p = makePlayer(0, "Biznes", PROFESSIONS[4], {isBot: false, personality: null, colorIndex: 0, dreamId: "d1", quadrant: "B"});
  delete p.assets[0].businessModel;
  return p;
};
const p = make();
p.cash = 20_000_000;
const baseCash = p.cash;
const baseValue = p.assets[0].price;
const baseNet = financeSummary(p).net;
operateBusiness(p, "accept");
assert.equal(businessStage(p), "procure");
assert.deepEqual(eligibleEvents(p, ["operations-procure"]).map(c => c.id), ["operations-procure"]);
const pending = JSON.stringify(p);
operateBusiness(p, "accept");
operateBusiness(p, "deliver");
assert.equal(JSON.stringify(p), pending, "Duplicate accept / unstocked delivery must not mutate");
operateBusiness(p, "restock");
assert.equal(p.cash, baseCash - 2_000_000);
assert.equal(p.assets[0].price, baseValue + 2_000_000);
assert.equal(businessStage(p), "deliver");
const stocked = JSON.stringify(p);
operateBusiness(p, "restock");
assert.equal(JSON.stringify(p), stocked);
p.freezeBusinessTurns = 1;
assert.match(operateBusiness(p, "deliver"), /to'xtagan/);
p.freezeBusinessTurns = 0;
operateBusiness(p, "deliver");
assert.equal(p.cash, baseCash + 1_600_000);
assert.equal(p.assets[0].price, baseValue);
assert.equal(financeSummary(p).net, baseNet, "Order cash is not recurring passive income");
const delivered = JSON.stringify(p);
operateBusiness(p, "deliver");
assert.equal(JSON.stringify(p), delivered, "No repeated order payout");
operateBusiness(p, "accept");
assert.equal(businessStage(p), "capacity");
const employees = p.assets[0].employees!;
operateBusiness(p, "hire");
assert.equal(p.assets[0].employees, employees + 1);
assert.equal(financeSummary(p).net, baseNet - 1_000_000);
assert.equal(p.assets[0].monthlyOperatingCosts, 17_000_000);
assert.equal(Object.values(p.assets[0].operatingCostParts!).reduce((a,b) => a+b, 0), 17_000_000);
operateBusiness(p, "upgrade");
assert.equal(p.assets[0].operations!.capacity, 40);
assert.equal(businessStage(p), "procure");
operateBusiness(p, "restock");
operateBusiness(p, "cancel");
assert.equal(p.assets[0].operations!.stock, 20);
operateBusiness(p, "accept");
assert.equal(businessStage(p), "deliver");
applyPayday(p);
assert.equal(p.assets[0].operations!.usedCapacity, 0);
assert.equal(p.assets[0].operations!.order!.monthsLeft, 2);
advanceBusinessMonth(p);
assert.equal(advanceBusinessMonth(p).length, 1);
assert.equal(p.assets[0].operations!.order, null);
assert.equal(p.assets[0].operations!.stock, 20);
assert.equal(validBusinessOperations(p.assets[0].operations), true);

const poor = make(); poor.cash = 0;
operateBusiness(poor, "accept");
const unchanged = JSON.stringify(poor);
for (const action of ["restock", "hire", "upgrade"] as const) operateBusiness(poor, action);
assert.equal(JSON.stringify(poor), unchanged);
const legacy = make(); delete legacy.assets[0].monthlyOperatingCosts; delete legacy.assets[0].operatingCostParts;
legacy.cash = 2_000_000;
operateBusiness(legacy, "hire");
assert.equal(legacy.assets[0].monthlyOperatingCosts, undefined, "Do not invent legacy costs");
const worker = make(); worker.quadrant = "E";
const eBefore = JSON.stringify(worker);
applyEvent(worker, {id: "test", title: "test", desc: "", icon: "Store", effect: {type: "business-operation", action: "accept"}});
assert.equal(JSON.stringify(worker), eBefore);
assert.ok(!eligibleEvents(worker, []).some(c => c.businessStage));

const storage = new Map<string, string>();
Object.defineProperty(globalThis, "localStorage", {value: {getItem: (k: string) => storage.get(k) ?? null, setItem: (k: string, v: string) => storage.set(k,v)}});
const state = makeGame([p]);
assert.ok(saveGame(state));
assert.deepEqual(loadSave()!.players[0].assets[0].operations, p.assets[0].operations);
const broken = structuredClone(state); broken.players[0].assets[0].operations!.stock = -1;
storage.set(SAVE_KEY, JSON.stringify(broken));
assert.equal(loadSave(), null);
console.log("Orders, stock, staff, capacity, cash conservation, expiry, legacy and saves: OK");
const simulated = make(); simulated.cash = 10_000_000;
const start = simulated.cash;
for (let cycle = 0; cycle < 1_000; cycle++) {
  operateBusiness(simulated, "accept");
  operateBusiness(simulated, "restock");
  operateBusiness(simulated, "deliver");
  advanceBusinessMonth(simulated);
  assert.ok(validBusinessOperations(simulated.assets[0].operations));
}
assert.equal(simulated.cash, start + 1_000 * 1_600_000);
assert.equal(simulated.assets[0].price, make().assets[0].price);
assert.equal(simulated.assets[0].operations!.stock, 0);
console.log("1,000 order cycles: cash, inventory and asset value conserved");
